# Importing the libraries

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import the dataset

In [17]:
churn_df = pd.read_csv('Churn_Modelling.csv')

In [26]:
X = churn_df.iloc[:,3:13].values
y = churn_df.iloc[:,13].values

In [27]:
print(X)
y

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


array([1, 0, 1, ..., 1, 1, 0])

# Encoding categorical data 

In [28]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_X1 = LabelEncoder()
X[:,1] = le_X1.fit_transform(X[:,1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [29]:
le_X2 = LabelEncoder()
X[:,2] = le_X2.fit_transform(X[:,2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [30]:
# creating dummy varibles for country column
OHE = OneHotEncoder(categorical_features = [1])
X = OHE.fit_transform(X).toarray() 

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [31]:
print(X)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


# Splitting the dataset into training and testing

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) 

# Feature scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

# Part - 2: Building the ANN

In [37]:
import keras

Using TensorFlow backend.


In [38]:
from keras.models import Sequential
from keras.layers import Dense

In [79]:
# initializing the ANN
classifier = Sequential() 

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 12))

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  """


In [80]:
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [81]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid')) 

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [82]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [83]:
# Fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.4818 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.4310 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4258 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4221 - accuracy: 0.8095
Epoch 5/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4189 - accuracy: 0.82150s - loss: 0.4
Epoch 6/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.4166 - accuracy: 0.8265
Epoch 7/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4153 - accuracy: 0.8280
Epoch 8/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.4136 - accuracy: 0.8294
Epoch 9/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4118 - accuracy: 0.8328
Epoch 10/100
8000/8000 [=================

8000/8000 [==============================] - 1s 165us/step - loss: 0.4004 - accuracy: 0.8353
Epoch 79/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.3997 - accuracy: 0.8346
Epoch 80/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4000 - accuracy: 0.8359
Epoch 81/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3997 - accuracy: 0.8350
Epoch 82/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4002 - accuracy: 0.8340
Epoch 83/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.4000 - accuracy: 0.8344
Epoch 84/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3996 - accuracy: 0.8363
Epoch 85/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3999 - accuracy: 0.8345
Epoch 86/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3998 - accuracy: 0.8345
Epoch 87/100
8000/8000 [==============================] - 1

# Part - 3 : Making predictions and evaluating the model

In [70]:
y_pred = classifier.predict(X_test)


In [71]:
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [72]:
# making the confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [73]:
cm

array([[1595,    0],
       [ 405,    0]])